title: Diving into Rust
description: Learn coding Rust
steps:
  - link: ''
    title: Setup the environment
    description: 'Setup the environment to get ready '
    course: ivancorrales
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
